name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Golangci-Lint
    runs-on: ubuntu-latest
    steps:

    - name: "Set up Go 1.15.5"
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.5'

    - name: "Check out code into the Go module directory"
      uses: actions/checkout@v2
    
    - uses: actions/checkout@v2
    - name: "Start Golangci-lint."
      uses: actions-contrib/golangci-lint@v1
      with:
        workdir: subdirectory/
