name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Golangci-Lint
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: "Start Golangci-lint."
      uses: actions-contrib/golangci-lint-action@v2
      with:
        version: v1.29
      
