# This is a basic workflow to help you get started with Actions

name: Test HTTP

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5' 
      
      - name: Check-out code
        uses: actions/checkout@v2
      
      - name: Go mod vendor
        run: go mod vendor

      # Runs a single command using the runners shell
      - name: Start HTTP
        run: go run main.go
